#!/usr/bin/env python3
"""
Self-Heal Fix Config Script
Repairs configuration files from backups or regenerates defaults.
"""

import json
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent
CONFIG_DIR = Path(__file__).parent.parent.parent.parent
BACKUP_DIR = CONFIG_DIR / "backups"
STATE_DIR = CONFIG_DIR / "state"

def ensure_backup_dir():
    """Ensure backup directory exists."""
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)

def create_backup(config_path):
    """Create a timestamped backup of a config file."""
    if not config_path.exists():
        return None

    ensure_backup_dir()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_name = f"{config_path.name}.{timestamp}.backup"
    backup_path = BACKUP_DIR / backup_name

    try:
        shutil.copy2(config_path, backup_path)
        print(f"   ✅ Created backup: {backup_path}")
        return str(backup_path)
    except Exception as e:
        print(f"   ❌ Could not create backup: {e}")
        return None

def find_backup(config_path):
    """Find the most recent backup for a config file."""
    if not BACKUP_DIR.exists():
        return None

    backup_pattern = f"{config_path.name}.*.backup"
    backups = list(BACKUP_DIR.glob(backup_pattern))

    if backups:
        return str(max(backups, key=lambda x: x.stat().st_mtime))
    return None

def get_default_config(config_path):
    """Generate default configuration based on file type."""
    if config_path.suffix == ".json":
        return {
            "version": "1.0",
            "created_at": datetime.now().isoformat(),
            "settings": {}
        }
    elif config_path.suffix == ".yaml" or config_path.suffix == ".yml":
        return """# OpenClaw Configuration
# Auto-generated by self-heal

version: "1.0"
settings: {}
"""
    elif config_path.suffix == ".env":
        return """# OpenClaw Environment Variables
# Auto-generated by self-heal

"""
    return "# Auto-generated config\n"

def parse_json_error(error_msg):
    """Parse JSON error message to find the issue."""
    # Common JSON error patterns
    patterns = [
        ("Expecting value", "JSON_DECODE_ERROR"),
        ("extra data", "EXTRA_DATA"),
        ("Expecting property name", "EXPECTING_PROPERTY"),
        ("Expecting ',' delimiter", "MISSING_COMMA"),
        ("Expecting ':' delimiter", "MISSING_COLON"),
    ]

    for pattern, code in patterns:
        if pattern.lower() in error_msg.lower():
            return code
    return "UNKNOWN"

def fix_json_syntax(config_path, error_msg):
    """Attempt to fix JSON syntax errors."""
    print(f"   Attempting to fix JSON syntax...")

    try:
        with open(config_path, 'r') as f:
            content = f.read()

        # Common fixes
        fixes_applied = []

        # Fix: Trailing commas
        import re
        trailing_comma_pattern = r',(\s*[}\]])'
        if re.search(trailing_comma_pattern, content):
            content = re.sub(trailing_comma_pattern, r'\1', content)
            fixes_applied.append("Removed trailing commas")

        # Fix: Missing commas between items
        # This is more complex and requires proper parsing

        # Write fixed content
        with open(config_path, 'w') as f:
            f.write(content)

        # Verify
        try:
            import json
            with open(config_path, 'r') as f:
                json.load(f)
            print(f"   ✅ Fixed JSON syntax ({', '.join(fixes_applied)})")
            return True
        except json.JSONDecodeError as e:
            print(f"   ❌ Could not fix JSON: {e}")
            return False

    except Exception as e:
        print(f"   ❌ Error fixing JSON: {e}")
        return False

def restore_from_backup(config_path):
    """Restore configuration from backup."""
    backup = find_backup(config_path)

    if backup:
        print(f"   Found backup: {backup}")
        try:
            shutil.copy2(backup, config_path)
            print(f"   ✅ Restored from backup")
            return True
        except Exception as e:
            print(f"   ❌ Could not restore from backup: {e}")
            return False

    print(f"   ⚠️ No backup found")
    return False

def regenerate_default(config_path):
    """Regenerate default configuration."""
    default_config = get_default_config(config_path)

    try:
        with open(config_path, 'w') as f:
            f.write(default_config)
        print(f"   ✅ Regenerated default config")
        return True
    except Exception as e:
        print(f"   ❌ Could not regenerate: {e}")
        return False

def validate_config(config_path):
    """Validate a configuration file."""
    try:
        if config_path.suffix == ".json":
            import json
            with open(config_path, 'r') as f:
                json.load(f)
            return True, None
        elif config_path.suffix in [".yaml", ".yml"]:
            # Try to parse YAML
            try:
                import yaml
                with open(config_path, 'r') as f:
                    yaml.safe_load(f)
                return True, None
            except Exception as e:
                return False, str(e)
    except Exception as e:
        return False, str(e)
    return True, None

def fix_config(config_path, error_msg=None):
    """
    Main function to fix a configuration issue.

    Args:
        config_path: Path to the config file
        error_msg: Error message from the failure

    Returns:
        dict: Fix result
    """
    print()
    print("=" * 50)
    print(f"🔧 Fixing Config: {config_path}")
    if error_msg:
        print(f"   Error: {error_msg}")
    print("=" * 50)

    result = {
        "config_path": str(config_path),
        "error": error_msg,
        "actions": [],
        "success": False
    }

    config_path = Path(config_path)

    # Step 1: Check if file exists
    print()
    print("Step 1: Checking file...")
    if not config_path.exists():
        print(f"   ⚠️ File does not exist: {config_path}")
        print("   Creating new config...")

        if regenerate_default(config_path):
            result["success"] = True
            result["actions"].append({"action": "create_new", "success": True})

        return result

    # Step 2: Create backup before any fixes
    print()
    print("Step 2: Creating backup...")
    backup = create_backup(config_path)
    if backup:
        result["actions"].append({"action": "backup", "success": True})
    else:
        result["actions"].append({"action": "backup", "success": False})

    # Step 3: Attempt to validate
    print()
    print("Step 3: Validating current config...")
    valid, validation_error = validate_config(config_path)

    if valid:
        print("   ✅ Config is valid")
        result["success"] = True
        result["actions"].append({"action": "validate", "success": True})
        return result

    print(f"   ❌ Validation failed: {validation_error}")
    result["actions"].append({
        "action": "validate",
        "success": False,
        "error": validation_error
    })

    # Step 4: Try to fix based on error type
    print()
    print("Step 4: Attempting fixes...")

    # Fix 1: JSON syntax errors
    if "json" in validation_error.lower() or "json" in (error_msg or "").lower():
        print("   Detected JSON error...")
        if fix_json_syntax(config_path, validation_error or error_msg):
            result["success"] = True
            result["actions"].append({"action": "fix_json_syntax", "success": True})

    # Fix 2: Try backup restoration
    if not result["success"]:
        print()
        print("   Attempting backup restoration...")
        if restore_from_backup(config_path):
            result["success"] = True
            result["actions"].append({"action": "restore_backup", "success": True})

    # Fix 3: Regenerate default
    if not result["success"]:
        print()
        print("   Attempting regeneration...")
        if regenerate_default(config_path):
            result["success"] = True
            result["actions"].append({"action": "regenerate", "success": True})

    # Step 5: Final validation
    if result["success"]:
        print()
        print("Step 5: Final validation...")
        valid, _ = validate_config(config_path)
        if valid:
            print("   ✅ Config is now valid")
        else:
            print("   ⚠️ Config still has issues")
            result["success"] = False
            result["actions"].append({"action": "final_validate", "success": False})

    # Summary
    print()
    print("=" * 50)
    print(f"📊 Fix Result: {'✅ SUCCESS' if result['success'] else '❌ FAILED'}")
    print("=" * 50)

    return result

def main():
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="Fix configuration issues")
    parser.add_argument("--file", required=True, help="Path to config file")
    parser.add_argument("--error", help="Error message from the failure")
    parser.add_argument("--json", action="store_true", help="Output JSON")

    args = parser.parse_args()

    result = fix_config(args.file, args.error)

    if args.json:
        print()
        print(json.dumps(result, indent=2, ensure_ascii=False))

    return 0 if result["success"] else 1

if __name__ == "__main__":
    sys.exit(main())
